name: Release and publish filigran-chatbot

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install
        run: yarn pack --out ./artifacts/filigran-chatbot-${{ github.ref }}.tgz

      - name: Release Filigran chatbot
        id: create_release
        run: gh release create ${{ github.ref }} ./artifacts/filigran-chatbot-*.tgz
        env:
          GITHUB_TOKEN: ${{ github.token }}