name: Release filigran-chatbot

on:
  push:
    tags:
      - '*'

jobs:
  release-chatbot:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          echo "Starting release version ${{ github.ref }}"
          yarn install
          yarn pack --out ./artifacts/filigran-chatbot-${{ github.ref }}.tgz
          ls -lart
          gh release create ${{ github.ref }} ./artifacts/*.tgz
        env:
          GITHUB_TOKEN: ${{ github.token }}